/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs and is checked in here so
// the scaffold typechecks cleanly once dependencies are installed.
